### ISSUE TITLE
可否增加Lenovo Y1S的汉化文件

### ISSUE THREAD

**Issue by anoidgit** [gorden5566/padavan#1]
您好，我也想自己定制padavan固件，但对这方面不了解，可否增加Y1S的配置文件呢

**Comment by gorden5566** [comment]
很抱歉，我没有这个型号的路由器，无法获取gpio等信息，也没办法测试，所以不能增加。

不过你可以自己尝试修改添加。

1. 复制RT-AC1200HP的配置

    `$ cd rt-n56u/trunk/configs/boards/`
    `$ cp -r RT-AC1200HP LENOVO-Y1S`

2. 相关配置文件如下

    LENOVO-Y1S/
    ├── board.h  *--gpio定义*
    ├── board.mk
    ├── kernel-3.4.x.config *--内核参数设置：CPU型号、RAM大小、内存卡或usb支持等*
    ├── libc.config -> ../uclibc-mipsel.config
    ├── SingleSKU_5G_CE.dat
    ├── SingleSKU_5G_FCC.dat
    ├── SingleSKU_5G_JP.dat
    ├── SingleSKU_CE.dat
    ├── SingleSKU_FCC.dat
    └── SingleSKU_JP.dat

3. 编辑`board.h`设置gpio信息

    gpio可在breed中获取，如果不知道breed，请自己百度下

    `gpio status`

    查看都有哪些状态，对应添加到`board.h`中

4. 编辑`kernel-3.4.x.config`设置CPU型号、RAM大小等信息

    例如：

    `CONFIG_RALINK_MT7620=y`
    `CONFIG_RT2880_DRAM_256M=y`
    `CONFIG_RALINK_RAM_SIZE=256`

5. 修改trunk目录下的`.config`，然后编译固件

   请参考`README.md`文件里的说明

**Comment by anoidgit** [comment]
好的，谢谢你啦，我尝试下弄好没问题，争取给你个反馈😊

**Comment by anoidgit** [comment]
您好，我已经做好修改开始编译了，请问SingleSKU是什么呢？有什么讲究吗？还是把RT-AC1200HP的复制过来就可以了。

**Comment by anoidgit** [comment]
因为修改defaults.h的原因会报一个错
U2EC -DAPP_OPENVPN -DAPP_XUPNPD -DAPP_SSHD -DAPP_RPL2TP -DSUPPORT_DDNS_SSL -DSUPPORT_PEAP_SSL -DSUPPORT_HTTPS -fPIC -Wall -I. -I./include -I/home/ano/padavan/trunk/linux-3.4.x/include/nvram   -c -o defaults.o defaults.c
In file included from ./include/ralink_boards.h:21,
                 from defaults.c:18:
./include/ralink_board.h:18:28: warning: extra tokens at end of #undef directive
defaults.c:53: error: 'DEF_LAN_ADDR' undeclared here (not in a function)
defaults.c:54: error: 'DEF_LAN_MASK' undeclared here (not in a function)
defaults.c:471: error: 'DEF_LAN_DHCP_BEG' undeclared here (not in a function)
defaults.c:472: error: 'DEF_LAN_DHCP_END' undeclared here (not in a function)
<builtin>: recipe for target 'defaults.o' failed
make[2]: *** [defaults.o] Error 1
