### ISSUE TITLE
是否存在劫持行为？@anoidgit

### ISSUE THREAD

**Issue by omnjpa27516** [gorden5566/padavan#13]
@anoidgit 你好，一直在使用你编译的固件，近期注意到存在劫持现象。京东会劫持到如下链接：
http://47.95.210.113:12224/jd_new?c=jd_shouye&u=ns.freedrive.cn%3Fs%3D797F1AF9F%26g%3D&a=ttest

**Comment by anoidgit** [comment]
@omnjpa27516 您好，最少我手动修改的代码没有做这件事情，官方开源的源码我觉得也不会做，毕竟开源嘛。但是一些广告过滤软件的规则（在这里说也不代表人家会做，只是说可能有这个能力），电脑上的软件（浏览器，或者其它网络控制软件），路由器使用的上游DNS都有可能指引跳转，我觉得问题不在路由器，甚至很可能这个锅最后要ISP背（如果电脑没中病毒或者被安装了流氓软的话），可以尝试换DNS（百度，114，阿里都可以尝试，我个人使用的，但不代表不会有任何问题），看问题还在不在，或者用其它电脑，手机或者浏览器访问，看是不是都有这种情况，如果只有特定浏览器或者电脑有，可能是浏览器或者电脑的问题。其实这问题我也不是很懂，只是业余编译固件，具体可以请教大神，他的commits我也经常会看。抱歉打扰 @gorden5566

**Comment by anoidgit** [comment]
也可能路由器的管理密码丢失，被人修改了hosts之类的文件或者防火墙规则做了跳转，我也经常逛京东，刚用我的手机和笔记本试了jd.com，没有发现跳转的情况。 @omnjpa27516

**Comment by omnjpa27516** [comment]
@anoidgit 感谢回答，应该是运营商的问题了，我在Google中搜到了相同的案例，劫持的 js 代码都基本相同。https://www.v2ex.com/t/377522

**Comment by anoidgit** [comment]
@omnjpa27516 不好意思，因为之前没有好好管理git记录，导致原来的项目记录太杂乱了，整理了一下搬家到[这里](https://github.com/anoidgit/TMRAF/releases)了，非常感谢支持。

**Comment by omnjpa27516** [comment]
@anoidgit 太棒了！感谢您的坚持更新，下次更新时能不能再带上d1呀？谢谢！

**Comment by anoidgit** [comment]
@omnjpa27516 我会再编译一个Newifi D1的版本增加到release里面去。但是不推荐D1使用padavan固件，主要考虑到两个原因：

1. padavan的固件可能会因为无线调校的原因，信号稍差一些，Newifi在4天线之前的信号好像本来就不怎么强，有的楼房钢材用的比较多，可能信号衰减比较严重，带宽需求高的无线连接使用体验会受影响；

2. D1的官方固件可以挖矿，有收入，所以喜欢刷三方固件的好像不多；

3. 我没有D1路由器，所以固件是否有问题我无法刷入自己的路由器测试，之前只是编译完成之后放出来，所以我不能保证D1的固件是没有问题的，刷入时请谨慎，如果出现问题，请尝试刷回官方固件或其它固件。

padavan维护的rt-n56u最近好像已经不怎么更新了，除非是影响使用的问题，再加上芯片比较老，很多新版本软件的工具链支持也有问题，所以这次编译的版本计划工作比较长的一段时间，除了有时跟进一些可以很轻松更新的软件，我自己维护的那个project可能会长期处于archive的状态。
