### ISSUE TITLE
如何打开BOARD_GPIO_PWR_USB

### ISSUE THREAD

**Issue by anoidgit** [gorden5566/padavan#3]
复制RT1200HP的board，如果定义了BOARD_GPIO_PWR_USB，编译的时候就会出错，请教是还需要在别的哪个文件里打开某个功能吗？

**Comment by gorden5566** [comment]
编译报错可以根据报错信心定位到是哪里的问题，比如某个文件的第几行有问题等等。
另外这一项不是必须的，具体看你的设备gpio定义。据我测试，newifi d1不加这个定义会导致usb接口没有供电，newifi mini和youku l1则不需要这个定义。

**Comment by anoidgit** [comment]
报错说是BOARD_GPIO_PWR_USB_ON方法没有定义，定位在了调用的位置，我找不到解决的办法，只好关掉了，现在倒是可以给手机充电，功能也都正常，就是这里感觉很奇怪，我再更新下pull request里的设置。

**Comment by gorden5566** [comment]
这要看具体的报错是什么了
